### ISSUE TITLE
Unable to install using Mason

### ISSUE THREAD

**Issue by matejko01** [ThePrimeagen/vim-be-good#141]
`:MasonInstallAll` simply ignores the package. Here is an excerpt from my **plugins.lua** file:

`local plugins = {
  {
    "ThePrimeagen/vim-be-good",
  }
return plugins`

**Comment by codebhav** [comment]
That's because Mason is a package manager for installing and managing language servers, linters, formatters, and other tools that integrate with Neovim's built-in LSP (Language Server Protocol) client.

However, it does not handle regular Vim/Neovim plugins. (vim-be-good is a Vim plugin).

If you're using Lazyvim add the `"ThePrimeagen/vim-be-good"` line to your `local default_plugin` and it should work just fine.

**Comment by matejko01** [comment]
I'm using NVChad, but I assume that the solution would be the same or similar?

**Comment by matejko01** [comment]
Thanks!
