### ISSUE TITLE
E492: Not an editor command: VimBeGood

### ISSUE THREAD

**Issue by cherrry9** [ThePrimeagen/vim-be-good#31]
**To Reproduce**
1. Create `min.vim`:
```vim
call plug#begin('~/.config/nvim/bundle/')

Plug 'ThePrimeagen/vim-be-good'

call plug#end()
```

2. Install [vim plug](https://github.com/junegunn/vim-plug#installation).
3. `nvim -u min.vim`
4. `:PlugInstall`
5. `:Up`
Output:
```
function remote#host#UpdateRemotePlugins[6]..<SNR>26_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5
Plugin "/home/jan/.config/nvim/bundle/vim-be-good/rplugin/node/vim-be-good" is already registered
remote/host: generated rplugin manifest: /home/jan/.local/share/nvim/rplugin.vim
````
6. `:VimBeGood`
Output:
```
E492: Not an editor command: VimBeGood
```

**Comment by ThePrimeagen** [comment]
Hmm...

Could you delete and re-install?

Also do you have neovim node module?  (I think you get it by default with coc).

**Comment by cherrry9** [comment]
I installed coc, reinstalled VimBeGood several times and I still have the same problem.

**Comment by lpanebr** [comment]
Did you run `:UpdateRemotePlugins` after `:PlugInstall`?

What's the output of `:checkhealth`?

**Comment by cherrry9** [comment]
I don't know what I did, but now VimBeGood works. Anyway thanks.

**Comment by ryanirl** [comment]
For anyone looking back at this thread, this was my situation and how I solved the problem: 

To recreate everything I did, I am on macOS and put "Plug 'ThePrimeagen/vim-be-good', {'do': './install.sh'}" in my plugins ran :Up which is shorthand for :UpdateRemotePlugins and I just received the VimBeGood not a command error, so I ran :checkhealth and low and behold I failed 'node.js provider' at the bottom so I ran 'npm install -g neovim' and :Up again and still didnt work.

Solution: What fixed it for me was after running 'npm install -g neovim' I had to remove the vim-be-good plugin from my .vimrc file and run :PlugClean to completely remove it then run :Up again. Then after it's been fully removed, you need to reinstall the vim-be-good plugin and run :Up again. 

The problem seems to be something with not having Node.js installed properly before you install vim-be-good, so you have to install Node.js correctly and then reinstall vim-be-good correctly.

**Comment by ThePrimeagen** [comment]
^--- Jeeeze.  I am trying to get the lua port done.  Its very very close and will contain some better features, it just took 20 hours instead of my estimated 10.... Who would of thought an engineer underestimated the difficulty.

**Comment by sainad2222** [comment]
I'm having the same problem. My nvim version is 0.4.4 . Is that causing the problem?
